### ISSUE TITLE
Unable to launch the game

### ISSUE THREAD

**Issue by gh0stf1sh** [Plutosion/Leashed#15]
Now all I was doing was testing if I could leash void worms (from Alex's Mobs) with the diamond leash and I couldn't even launch the game without it crashing right away. It doesn't even leave a crash report.

But the thing is I only had two mods at the time which was Alex's Mobs and Leashed (three if you count Citadel which is needed to run Alex's Mobs).

The second I removed Leashed or Alex's Mobs I was able to launch the game as normal.

**Comment by Mrbysco** [comment]
Any crash log?

**Comment by gh0stf1sh** [comment]
No the game crashes before it can even properly launch so there is no crash log in the folder.

**Comment by Mrbysco** [comment]
Any logs? As it should have logged any problem

**Comment by gh0stf1sh** [comment]
Oh I'm dumb I realized forgot the logs folder exists here you go.
It's also on 1.18.1 too I think I forgot to mention that.

[19Jan2022 21:32:23.142] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Ender__Nova, --version, 1.18.1-forge-39.0.44, --gameDir, C:\Users\tpenn\AppData\Roaming\.minecraft, --assetsDir, C:\Users\tpenn\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, 334bd85afcae486ab806b83733b37e09, --accessToken, ????????, --clientId, ZDIzODFkMDItZWNhMy00ODY1LWFhZDAtYWI3MTUwZjY2YWJl, --xuid, 2535413106407595, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 39.0.44, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407]
[19Jan2022 21:32:23.158] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.1 by Microsoft
[19Jan2022 21:32:23.376] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/tpenn/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=CLIENT
[19Jan2022 21:32:26.259] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[19Jan2022 21:32:26.274] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.1-forge-39.0.44, --gameDir, C:\Users\tpenn\AppData\Roaming\.minecraft, --assetsDir, C:\Users\tpenn\AppData\Roaming\.minecraft\assets, --uuid, 334bd85afcae486ab806b83733b37e09, --username, Ender__Nova, --assetIndex, 1.18, --accessToken, ????????, --clientId, ZDIzODFkMDItZWNhMy00ODY1LWFhZDAtYWI3MTUwZjY2YWJl, --xuid, 2535413106407595, --userType, msa, --versionType, release]
[19Jan2022 21:32:30.149] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed leashed.mixins.json:MobEntityMixin -> net.minecraft.world.entity.Mob: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method m_21528_ in leashed.mixins.json:MobEntityMixin cannot reduce visibiliy of PUBLIC target method
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method m_21528_ in leashed.mixins.json:MobEntityMixin cannot reduce visibiliy of PUBLIC target method
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:485) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:458) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:419) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:349) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.0.jar:9.1.0+9.1.0+main.6690ee51]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.0.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:280) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar%2337!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:28) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:18) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at net.minecraft.data.BuiltinRegistries.m_194668_(BuiltinRegistries.java:38) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at net.minecraft.data.BuiltinRegistries.m_194659_(BuiltinRegistries.java:93) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:92) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:517) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:45) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:138) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Mrbysco** [comment]
I've just uploaded a new version that should fix this issue

**Comment by Mrbysco** [comment]
![image](https://user-images.githubusercontent.com/9308260/150367831-a634520a-7b45-419c-b8b8-6a85757a568c.png)

**Comment by gh0stf1sh** [comment]
THANK YOU SO MUCH I CAN FINALLY HAVE MY PET VOID WORM
